Develop
r-martins/PagSeguro-Magento-Transparente-M2 pull request #76
Opened 2021-02-28 00:46 UTC by phaelfp

Baixei o branch develop em cima do meu feature/twocard e fiz o merge resolvendo os conflitos.

Mantive o branch para caso ocorra algum problema.

2021-03-01 01:03 UTC, r-martins requested changes
Oi, Rapha. Tudo bom?
Este é um grande commit, então eventualmente teremos mais de uma bateria de rejects e reviews.. 
Nos primeiros testes...
1. você comitou alterações nas permissões de arquivos que não mexeu (e de todos os que mexeu). Certifique-se de trabalhar com `core.filemode = false` no .git/config para evitar este tipo de problema acidentalmente
2. Temos alguns termos sem tradução.. Ex:  "PagSeguro - Two Credit Card - Ricardo Martins", "Amount For This Credit Card". 
3. Tentei finalizar uma compra do didi sport watch (veja [meu checkout](https://www.evernote.com/l/ASHHKf53uR9B2KQDQOocHk4IJmp3MsfEyuQ)), mas tive erro de [parcela inválida](https://www.evernote.com/l/ASGb1_XUMWtLfbpyC9frbwpCnhN-0cQJifc).
Nos logs pude ver que o primeiro pedido foi feito com sucesso no valor de R$50 (e que provavelmente será cobrado do cliente pois não haverá estorno do pedido não realizado, né?).  O log deste teste está [aqui](https://pastebin.com/tMwua7HM). 
Não consegui finalizar a compra mesmo alterando o frete. Passou a dar erro de parcela no primeiro cartão.

2021-03-02 22:37 UTC, phaelfp commented
Ricardo eu adicionei os dois termos na tradução não sei como posso atualizar o PR.
Adicionei o core.filemode = false, realmente estava como true.
Testei o branch develop e não tive nenhum erro. segue [Vídeo](https://drive.google.com/file/d/1JeELCRfzUfXFx-VBmamn1IB1Aldu_f-2/view?usp=sharing) de evidencia. Tem como remover os arquivos do dir /pub/static/frontend antes do bin/magento setup:static-content:deploy -f pt_BR en_US para ter certeza que não foi cache de JS.

2021-03-19 07:29 UTC, r-martins requested changes
Oi, Rapha. Tudo bom?
Obrigado pelas correções.
Ainda estou no meio do caminho com os testes, mas como estou terminando minha sexta, vou deixar um parcial aqui pra você. Retomarei os testes amanhã (sábado).

1. Ao dar um blur no valor cobrado no segundo cartão, as parcelas selecionadas no primeiro é perdido.
![Gif](http://g.recordit.co/73EYD5kVQq.gif)

2. Melhoria: Conseguimos melhorar o info block mostrando o status de cada cartão? Digo, mostrar se o primeiro foi aprovado/cancelado, etc. Tente colocar um negrito no texto "1º cartão" e "2º cartão", a fim de separar um pouco as informações. 
3. É importante que o cliente receba o e-mail de cancelamento do pedido nos casos que isso ocorre. Aparentemente não está recebendo. Fiz o teste de disparo do sales_send_order_emails mas não recebi nada além do e-mail de novo pedido no mailhog.
4. Os campos de cartão ficaram encavalados no mobile.
<img width="591" alt="image" src="https://user-images.githubusercontent.com/191149/111744644-a7d87f00-88df-11eb-8ef9-cdb0c588b095.png">
5. Poderia trocar os input type="text" pra type="tel" nos campos de numero do cartao, data de nascimento, valor da parcela e cpf? Assim o teclado numérico seria exibido no mobile.
6. No mobile, quando eu apago o valor a pagar pra colocar outro eu não consigo alterar pra nada que não comece com "1". 
[Video](https://www.loom.com/share/35577b466dca4b118d0ef6c4389a3a7a)

2021-03-27 04:43 UTC, r-martins requested changes
Fala Rapha.. tudo bom?
Peço que corrija os conflitos antes do próximo update.. mas testei mesmo assim..

1. Persiste bug ao trocar valor das parcelas no segundo cartão, eu perco as parcelas selecionadas no primeiro
2. Ao trocar o valor do primeiro cartão, as parcelas do segundo não são atualizadas
3. O getBin está sendo chamado com 5 dígitos ocasionando erro 
Os 3 itens acima tem um [Vídeo](https://www.loom.com/share/9a9b766ccc6a4443a30b968c852ded66)

Depois de forçar a compilação dos arquivos estáticos e limpar cookies e local storage (coindidencia ou nao) teve uma hora que eu não conseguia calcular as parcelas do segundo cartão de jeito algum.
Nas vezes que eu consegui, não consegui finalizar por conta do erro de parcela invalida do primeiro cartão que não tinha sido recalculado.

4. Fiz um teste onde os dois cartões foram pagos; forcei atualização deles pelo painel; depois marquei a transação do cc1 como devolvido; e chamei a url de notification com a notificação da devolução. 
Apesar dele ter conseguido fazer o refund da segunda, o pedido permaneceu como Processing e mostrando os dois cartões como Pago. [Logs aqui](https://pastebin.com/mRGCeHPw)

Os demais pontos que tinha comentado anteriormente estão ok. ;)

2021-04-06 01:55 UTC, r-martins requested changes
Fala Rapha.. estamos indo bem..
1. Tradução do placeholder YYYY pra AAAA
2. Erro "valor da parcela inválido" meus testes. O valor dar parcela enviado foi diferente daquele selecionado no front end. Em alguns casos quando deu erro continuou a se perder no calculo das parcelas. [Video](https://www.loom.com/share/dbd260e0d4df4f74adaf1d5d550cd1d8)

2021-04-13 00:59 UTC, r-martins requested changes
Fala Rapha. Tudo bom?
Aparentemente o módulo está pegando o valor das parcelas anteriores e usando no novo pedido.
[Vídeo](https://www.loom.com/share/3b450b2e1abb4adbba1f4ad9ddce7625)

2021-04-16 01:52 UTC, r-martins requested changes
Fala Rapha. Blz?
Agora consegui ver o bloqueio do finalizar compra. Ficou bacana.

Ainda tive alguns imprevistos..
1. Ao usar a data de validade 02/22 no segundo cartão, trocar o valor total e em seguida tentar finalizar, tive erro de validação da data de validade. 
<img width="402" alt="image" src="https://user-images.githubusercontent.com/191149/114959762-0b3ada00-9ea9-11eb-9ac9-701ef29a555d.png">

1.2 Notei que o token está tentando ser gerado a cada keypress/keyup dentro das datas de validade do cartão, mesmo que nada mude.

Um video que ilustra os dois casos: [aqui](https://www.loom.com/share/df5a66debedd42818ef352dbbbff3a84)

2021-04-21 23:16 UTC, r-martins requested changes
Rapha, novamente problemas semelhantes. Não foi dificil reproduzir.
Nos dois primeiros testes que fiz já foi enviado parcelas diferentes daquelas exibidas no front. Veja video em https://www.loom.com/share/d8a24cb096b44313b887419af0f85a03

2021-04-21 23:22 UTC, r-martins commented
Só complementando... os valores enviados no payment-information (aba Network) foram os valores que de fato foram enviados pro pagseguro, ou seja, estão errados.

2021-04-30 05:54 UTC, r-martins requested changes
Oi Rapha.. Hoje voltei a testar de novo esse PR com minha conta pessoal mesmo em Sandbox (a fim de não prolongar ainda mais esta nossa novela).... Vamos lá..

1. Seguimos com outro erro de parcela. Desta vez não encostei nos campos de valor da parcela, e tentei finalizar a compra do relógio em 2x. E tive erro de installment quantity invalid value: 2. [Imagem](https://www.evernote.com/l/ASGf-ZJRHi1D0o7ivgDY65urvyVanBMIuwcB/image.png) / [Video](https://www.loom.com/share/b968fa0103ea487c9cb0ee73e5d1c76b)

2021-05-21 02:38 UTC, r-martins commented
Oi, @phaelfp . Você poderia resolver os conflitos com o `develop` antes?

2021-05-21 02:38 UTC, r-martins requested changes
Poderia resolver os conflitos com `develop` antes?

2021-05-27 07:02 UTC, r-martins requested changes
Oi, Rapha... Parece que agora só falta as arestas..
Ainda não consegui testar tudo, mas um dos testes falhou.

1. Ao ter o pedido atualizado no magento com dois cartões pagos, fui no pagseguro e mudei o status do segundo cartao pra Devolvido. Ao atualizar o segundo cartão no painel do Magento tive o erro "Tentativa de atualização manual de pedido falhou. Erro: Erro no estorno do pagamento.".  Nos logs tive "invalid transaction status to refund" quando o modulo tentou fazer refund do pedido que ja estava como Devolvido.

2021-06-03 04:09 UTC, r-martins requested changes
Oi, @phaelfp .
Eis novos problemas (mais do mesmo):

1. Qdo fecho a compra com cupom de desconto (10.5% off) tive erro de installment invalid value (veja [video](https://www.loom.com/share/2b3929d84df04db79eb68925ec724d0c) com detalhe)
2. Token do cartão não é atualizado quando troca o cvv ou número do cartão. ([Video](https://www.loom.com/share/df667b6372834be59af795fd242320a3))

[Aqui](https://www.evernote.com/l/ASGI0ctEHMJAx7rn1FS6wPVsQ9R-grm-UvUB/image.png) você encontra uma lista que usei para os testes dos dois cartões no M1. Estou usando ela no M2 também. Fique à vontade para testar estes pontos antes do próximo PR, evitando retrabalho e mais um fluxo.

2021-09-23 03:54 UTC, merged