Botão de limpeza de cache de parcelamento
r-martins/PagSeguro-Magento-Transparente-M2 pull request #79
Opened 2021-04-01 18:04 UTC by lawsann

O cache "fake" de parcelamento, que disparava a limpeza de dados nos atributos de produto quando o comando "cache clean" do Magento era acionado, foi substituído por um tipo de cache adicional - similar às imagens e arquivos estáticos do Magento.

Assim, para limpar o cache de parcelas dos produtos, o usuário deverá acessar a página de controle do cache na administração e, deliberadamente, limpar o cache de parcelas clicando no botão específico para esta finalidade.

2021-04-06 04:06 UTC, r-martins requested changes
embora tenha funcionado como esperado, temos um problema de segurança (ACL) e MEQP em vários pontos do código. Pode revisar?
Todos são correções simples.

2021-04-06 04:06 UTC, r-martins commented on Model/Cache/Type/Installments.php
> +        if( !$this->_productAttributeExists(self::ATTR_OPTIONS) ||
MEQP

2021-04-06 04:06 UTC, r-martins commented on Model/Cache/Type/Installments.php
> +        if($productCollection->getSize() <= 0)
MEQP

2021-04-06 04:06 UTC, r-martins commented on Model/Cache/Type/Installments.php
> +        foreach($productCollection as $product) {
MEQP

2021-04-06 04:06 UTC, r-martins commented on Model/Cache/Type/Interests.php
> -        if($productCollection->getSize() > 0)
MEQP

2021-04-06 04:06 UTC, r-martins commented on Model/Cache/Type/Interests.php
> -            foreach($productCollection as $product)
MEQP

2021-04-06 04:06 UTC, r-martins commented on Model/Cache/Type/Interests.php
> -        $productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection');
Sugestao: Podemos tentar diminuir a coleção filtrando somente aqueles que tem algum valor no rm_interest_options

2021-04-06 17:03 UTC, lawsann commented on Model/Cache/Type/Interests.php
> -        $productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection');
Não entrei neste mérito, pois a tarefa é mais voltada à interface. Mas, já que citou, sugeri uma abordagem e a submeti (commit).

No meu entendimento, buscar, iterar e preencher valores não representam bem o ato de "flush something". Portanto, deixei como sugestão remover todos os valores do banco e invalidar as tags do cache que julgarmos pertinentes.

2021-04-06 17:59 UTC, lawsann commented on Controller/Adminhtml/Cache/FlushProductInstallments.php
> +    /**
Corrigido, junto com outro problema de permissão mais específico.

2021-04-13 04:49 UTC, r-martins requested changes

2021-04-13 14:27 UTC, lawsann commented on Plugin/Block/Cache/Permissions.php
> +            $result = $result || $this->hasAccessToFlushInstallments();
> É um OU outro ou é $result && ... ?
> Do jeito que está, mesmo se ele não tiver permissão, mas tiver permissão no additionalActions vai retornar true. É isso mesmo ou interpretei errado?

Correto. É isto mesmo: esta área trata da permissão de ver o bloco. Se o usuário tem permissão de ver algo dentro do bloco (qualquer um dos botões), ele deve visualizar o bloco. Os botões possuem permissões próprias.

> Fiz um teste com um usuário que pertencia a um grupo que não tinha permissão e ele pôde ver o botão e também clicar e limpar as parcelas. Este usuário tinha permissão em todo resto dentro de "Ferramentas"

Este comportamento está incorreto. Irei revisar agora.

2021-06-09 07:14 UTC, merged